#!/bin/sh

set -e


php_enable() { return 0; }

if [ "$1" = "purge" ]; then
    phpini=/etc/php/8.4/phpdbg/php.ini
    # remove the flag to remember the original state
    if [ -e /etc/php/8.4/phpdbg/.start ]; then
	rm -f /etc/php/8.4/phpdbg/.start
    fi
    for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist;  do
	rm -f $phpini$ext
    done
    rm -f $phpini
    if which ucf >/dev/null; then
	ucf --purge $phpini
    fi
    if which ucfr >/dev/null; then
	ucfr --purge php8.4-phpdbg $phpini
    fi

    for dir in \
	/etc/php/8.4/phpdbg/conf.d \
	/etc/php/8.4/phpdbg \
	/etc/php/8.4 \
	/etc/php;
    do
	if [ ! -L $dir ] && [ -d $dir ]; then
	    rmdir --ignore-fail-on-non-empty $dir
	fi
    done
fi



exit 0
