#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.5.2ubuntu1
dpkg-maintscript-helper dir_to_symlink /usr/share/phpmyadmin/js/vendor/codemirror/addon/hint ../../../../../javascript/codemirror/addon/hint 4:5.0.4\+dfsg2-2\~ -- "$@"
dpkg-maintscript-helper dir_to_symlink /usr/share/phpmyadmin/js/vendor/codemirror/addon/lint ../../../../../javascript/codemirror/addon/lint 4:5.0.4\+dfsg2-2\~ -- "$@"
dpkg-maintscript-helper dir_to_symlink /usr/share/phpmyadmin/js/vendor/codemirror/lib ../../../../javascript/codemirror/lib 4:5.0.4\+dfsg2-2\~ -- "$@"
dpkg-maintscript-helper dir_to_symlink /usr/share/phpmyadmin/themes/original/jquery/images ../../../../javascript/jquery-ui/themes/base/images 4:5.0.4\+dfsg2-2\~ -- "$@"
dpkg-maintscript-helper dir_to_symlink /usr/share/phpmyadmin/themes/pmahomme/jquery/images ../../../../javascript/jquery-ui/themes/base/images 4:5.0.4\+dfsg2-2\~ -- "$@"
dpkg-maintscript-helper symlink_to_dir /usr/share/phpmyadmin/js/vendor/openlayers ../../../javascript/openlayers 4:5.1.1\+dfsg2-1\~ -- "$@"
# End automatically added section
